name: Build and Publish

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish
        run: .\build.ps1
        shell: powershell
        env:
          CHOCOPUSHKEY: ${{ secrets.CHOCOPUSHKEY }}